version: '3.8'
services:
  authn-service:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - dbUrl=postgresql://kim:123@db:5432/authnService?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: psqlAuthn
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kim
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=authnService
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data: